apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - serviceaccount.yaml
  - servicemonitor.yaml

configurations:
  - namereference.yaml
  - varreference.yaml

images:
  - name: java-grpc-connector-template
    newName: docker-na-public.artifactory.swg-devops.com/hyc-cp4mcm-team-docker-local/ibmcom/java-grpc-connector-template
    newTag: updateTemplateJuly

vars:
  - name: SERVICE_NAME
    objref:
      kind: Service
      name: java-grpc-conn-template
      apiVersion: v1
    fieldref:
      fieldpath: metadata.name
  - name: SERVICE_NAMESPACE
    objref:
      kind: Service
      name: java-grpc-conn-template
      apiVersion: v1
    fieldref:
      fieldpath: metadata.namespace
